import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {makeCommunity,RULES} from '../lib/community/service.mjs';
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');db.transaction=fn=>(...args)=>{db.exec('SAVEPOINT tx');try{const r=fn(...args);db.exec('RELEASE tx');return r;}catch(e){db.exec('ROLLBACK TO tx; RELEASE tx');throw e;}};db.exec(readFileSync(new URL('../lib/community/schema.sql',import.meta.url),'utf8'));db.exec('CREATE TABLE broadcasts(id TEXT,active INTEGER,heartbeat INTEGER)');let now=Date.now();const live=randomUUID();db.prepare('INSERT INTO broadcasts VALUES(?,1,?)').run(live,now);const s=makeCommunity({db,rateSecret:'x'.repeat(32),now:()=>now});const a=s.signup('a',RULES),b=s.signup('b',RULES);const post=(member=a,text='Привет')=>{const id=randomUUID();s.post(member.token,{id,body:text,live});return id;};return {db,s,a,b,live,post,tick:n=>{now+=n;db.prepare('UPDATE broadcasts SET heartbeat=?').run(now);}};}
test('guest cannot read or post comments',()=>{const f=fixture();assert.throws(()=>f.s.list('',f.live),/unauthorized/);assert.throws(()=>f.s.post('',{id:randomUUID(),body:'a',live:f.live}),/unauthorized/);f.db.close();});
test('registration stores only a hash, not recovery code or raw session',()=>{const f=fixture();const r=f.db.prepare('SELECT * FROM tt_members WHERE id=?').get(f.a.member.id);assert.equal(r.recovery_hash.length,64);assert.ok(!JSON.stringify(r).includes(f.a.code));assert.equal(f.s.me(f.a.token).nickname,f.a.member.nickname);f.db.close();});
test('code login rotates previous sessions; wrong code rejected',()=>{const f=fixture();assert.throws(()=>f.s.login('ip','wrong'),/invalid_code/);const n=f.s.login('ip',f.a.code);assert.equal(f.s.me(f.a.token),null);assert.equal(f.s.me(n.token).id,f.a.member.id);f.db.close();});
test('expired session cannot access comments',()=>{const f=fixture();f.tick(7*86400000+1);assert.equal(f.s.me(f.a.token),null);assert.throws(()=>f.s.list(f.a.token,f.live),/unauthorized/);f.db.close();});
test('rules acceptance and registration rate limit required',()=>{const f=fixture();assert.throws(()=>f.s.signup('ip','old'),/rules_required/);for(let i=0;i<3;i++)f.s.signup('ip',RULES);assert.throws(()=>f.s.signup('ip',RULES),/rate_limit/);f.db.close();});
test('comment immediately visible to registered listeners without approval',()=>{const f=fixture();f.post();assert.equal(f.s.list(f.a.token,f.live).items[0].state,'published');assert.equal(f.s.list(f.b.token,f.live).items.length,1);assert.equal(f.s.queue().length,1);f.db.close();});
test('comment retry is idempotent and mismatched ID rejected',()=>{const f=fixture(),id=f.post();f.s.post(f.a.token,{id,live:f.live,body:'Привет'});assert.equal(f.s.list(f.a.token,f.live).items.length,1);assert.throws(()=>f.s.post(f.a.token,{id,live:f.live,body:'Изменение'}),/conflict/);f.db.close();});
test('spam cooldown, long text and links rejected',()=>{const f=fixture();f.post();assert.throws(()=>f.post(),/rate_limit/);f.tick(6000);assert.throws(()=>f.post(f.a,'x'.repeat(501)),/invalid_comment/);assert.throws(()=>f.post(f.a,'https://spam.example'),/invalid_comment/);f.db.close();});
test('ended live forbids new comments',()=>{const f=fixture();f.db.exec('UPDATE broadcasts SET active=0');assert.throws(()=>f.post(),/live_ended/);assert.equal(f.s.list(f.a.token,f.live).active,false);f.db.close();});
test('block hides author and unblock restores visible comments',()=>{const f=fixture(),id=f.post();f.s.moderate({id,action:'publish'});f.s.block(f.b.token,f.a.member.id);assert.equal(f.s.list(f.b.token,f.live).items.length,0);f.s.block(f.b.token,f.a.member.id,false);assert.equal(f.s.list(f.b.token,f.live).items.length,1);f.db.close();});
test('reports reach moderation; rejection requires a reason',()=>{const f=fixture(),id=f.post();f.s.moderate({id,action:'publish'});f.s.report(f.b.token,id,'abuse');assert.equal(f.s.queue()[0].reports,1);assert.throws(()=>f.s.moderate({id,action:'reject'}),/reason_required/);f.s.moderate({id,action:'reject',reason:'Нарушение правил'});assert.equal(f.s.list(f.b.token,f.live).items.length,0);assert.equal(f.s.list(f.a.token,f.live).items[0].reason,'Нарушение правил');f.db.close();});
test('banned profile cannot post, but may export and delete',()=>{const f=fixture(),id=f.post();f.s.moderate({id,action:'ban',reason:'Спам'});assert.throws(()=>f.post(),/banned/);assert.equal(f.s.exportData(f.a.token).profile.id,f.a.member.id);f.s.erase(f.a.token);assert.equal(f.s.me(f.a.token),null);f.db.close();});
test('cannot remove another user comment',()=>{const f=fixture(),id=f.post();f.s.removeOwn(f.b.token,id);assert.equal(f.s.list(f.a.token,f.live).items.length,1);f.db.close();});
test('account deletion removes comments, reports, blocks and sessions',()=>{const f=fixture(),id=f.post();f.s.moderate({id,action:'publish'});f.s.report(f.b.token,id,'spam');f.s.block(f.b.token,f.a.member.id);f.s.erase(f.a.token);for(const table of ['tt_comments','tt_comment_reports','tt_member_blocks'])assert.equal(f.db.prepare('SELECT COUNT(*) n FROM '+table).get().n,0);assert.equal(f.s.me(f.a.token),null);assert.ok(f.s.me(f.b.token));f.db.close();});
test('30-day retention deletes old comments and linked reports',()=>{const f=fixture(),id=f.post();f.s.moderate({id,action:'publish'});f.s.report(f.b.token,id,'spam');f.tick(31*86400000);f.s.prune();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM tt_comments').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM tt_comment_reports').get().n,0);f.db.close();});
console.log('TOTAL '+passed+' passed — real SQLite, no production data.');
