'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {AudioLines,Mic,Radio,BookOpen,Headphones,Settings,Download,ArrowUpRight,Plus,Upload,Square,Pause,Play,Heart,Check,Volume2,FileAudio,ChevronRight,Monitor,ExternalLink,Trash2,Eye,EyeOff,Pencil,Loader2,Menu,Unplug,LogOut} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {useCapture} from '@/hooks/use-capture';
import {useLive} from '@/hooks/use-live';
import {PodcastPlayer} from '@/components/studio/podcast-player';
import {InputPicker,SignalMeter,AudioControls} from '@/components/studio/audio-console';
import {NotificationSettings} from '@/components/studio/notification-settings';
import {Slider} from '@/components/ui/slider';
import {api,clock,errorText} from '@/lib/client';

type Post={id:string;kind:string;title:string;description:string;body:string;audioKey:string|null;duration:number;published:number;createdAt:number};
type Data={items:Post[];isOwner:boolean;needsSetup:boolean;signedIn:boolean;donation:string;live:{id:string;title:string}|null};
const nav=[{id:'studio',label:'Студия',icon:Mic},{id:'podcasts',label:'Подкасты',icon:Headphones},{id:'stories',label:'Истории',icon:BookOpen},{id:'live',label:'Прямой эфир',icon:Radio},{id:'settings',label:'Настройки',icon:Settings}];
function Brand(){return <div className="brand brand-with-logo"><img src="/brand/logo.png?v=0.4.1" width="112" height="112" alt="True Thrills"/></div>;}
function NavButton({item,active,onClick}:{item:typeof nav[number];active:boolean;onClick:()=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenuItem><SidebarMenuButton isActive={active} onClick={()=>{onClick();setOpenMobile(false);}} className="nav-item"><item.icon/><span>{item.label}</span>{active&&<span className="nav-line"/>}</SidebarMenuButton></SidebarMenuItem>;}
export default function Studio(){
 const noticeHandler=useRef<(url:string)=>Promise<void>>(async()=>{});
 const [discardText,setDiscardText]=useState(false);
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[view,setView]=useState('studio'),[audience,setAudience]=useState(false),[androidClient,setAndroidClient]=useState(false);
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[body,setBody]=useState(''),[editing,setEditing]=useState<Post|null>(null),[editor,setEditor]=useState<'story'|'podcast'|null>(null),[saving,setSaving]=useState(false),[donation,setDonation]=useState(''),[liveTitle,setLiveTitle]=useState(''),[filter,setFilter]=useState('all'),[reading,setReading]=useState<Post|null>(null),[playing,setPlaying]=useState<Post|null>(null),[confirmDelete,setConfirmDelete]=useState<Post|null>(null),[dirty,setDirty]=useState(false),[replaceRecording,setReplaceRecording]=useState(false);
 const capture=useCapture(),live=useLive(),player=useRef<HTMLAudioElement|null>(null),fileInput=useRef<HTMLInputElement|null>(null);
 const author=!!data?.isOwner&&!audience;
 useEffect(()=>{const native=window as Window & {chrome?:{webview?:{postMessage:(message:string)=>void}}};native.chrome?.webview?.postMessage(capture.recording||!!live.hosting?'true-thrills:active':'true-thrills:idle');},[capture.recording,live.hosting]);
 const [liveNow,setLiveNow]=useState<Data['live']>(null),[liveError,setLiveError]=useState(false);
 const liveStatus=liveNow;
 const liveRequest=useRef(false);
 const refreshLive=useCallback(async()=>{if(liveRequest.current)return;liveRequest.current=true;try{const r=await api<{live:Data['live']}>('live?status=1');setLiveNow(r.live);setLiveError(false);}catch{setLiveError(true);}finally{liveRequest.current=false;}},[]);
 useEffect(()=>{void refreshLive();const timer=setInterval(()=>void refreshLive(),3000);const resume=()=>{if(document.visibilityState==='visible')void refreshLive();};document.addEventListener('visibilitychange',resume);window.addEventListener('focus',resume);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',resume);window.removeEventListener('focus',resume);};},[refreshLive]);
 useEffect(()=>{if(live.hosting&&!capture.ready){void live.stop().catch(()=>{});toast.error('Микрофон отключён — эфир завершён');}},[capture.ready,live.hosting]);
 const load=useCallback(async()=>{try{const d=await api<Data>('library');setData(d);setError('');return d as Data;}catch(e){setError(errorText(e));return null;}},[]);
 useEffect(()=>{load().then(d=>{if(d){setDonation(d.donation);const q=new URLSearchParams(location.search);setAndroidClient(q.get('client')==='android');if(q.get('mode')==='listen'){setAudience(true);setView(['live','stories','settings'].includes(q.get('view')??'')?q.get('view')!:'podcasts');}else if(!d.isOwner&&!d.needsSetup)setView('podcasts');if(q.has('post')||q.has('broadcast'))void noticeHandler.current(location.href);}});const timer=setInterval(()=>void load(),15000);return()=>clearInterval(timer);},[load]);
 useEffect(()=>{if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{});const handler=(e:MessageEvent)=>{if(e.data?.type==='tt-notification'&&typeof e.data.url==='string')void noticeHandler.current(e.data.url);};navigator.serviceWorker.addEventListener('message',handler);return()=>navigator.serviceWorker.removeEventListener('message',handler);},[]);

 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||saving){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,saving]);
 useEffect(()=>{if(editor==='story'&&!editing){try{localStorage.setItem('tt-story-draft',JSON.stringify({title,description,body}));}catch{}}},[editor,editing,title,description,body]);
 const run=async(fn:()=>Promise<unknown>,message?:string)=>{try{await fn();if(message)toast.success(message);await load();}catch(e){toast.error(errorText(e));}};
 function openEditor(kind:'story'|'podcast',p?:Post){setEditing(p??null);setTitle(p?.title??'');setDescription(p?.description??'');setBody(p?.body??'');setDirty(false);setEditor(kind);if(kind==='story'&&!p){try{const saved=JSON.parse(localStorage.getItem('tt-story-draft')||'null');if(saved){setTitle(saved.title||'');setBody(saved.body||'');setDescription(saved.description||'');}}catch{}}}
 async function setup(){setSaving(true);await run(async()=>{await api('library',{action:'setup'});setView('studio');},'Студия готова');setSaving(false);}
 async function uploadFile(b:Blob){if(!b.size)throw new Error('Аудиофайл пуст');if(b.size>80*1024*1024)throw new Error('Максимум 80 МБ на запись');let mime=b.type||'audio/mpeg';if(mime==='video/webm')mime='audio/webm';if(mime==='audio/x-m4a')mime='audio/mp4';const r=await fetch('/api/audio',{method:'POST',headers:{'Content-Type':mime,'X-Upload-Size':String(b.size)},body:b});const d=await r.json() as {error?:string;key:string};if(!r.ok)throw new Error(d.error||'Аудио не загрузилось');return d.key as string;}
 async function save(published:boolean){
  if(!title.trim()){toast.error('Укажите название');return;}if(editor==='story'&&!body.trim()){toast.error('Добавьте текст истории');return;}setSaving(true);
  try{const audioKey=editor==='podcast'?(editing?.audioKey??(capture.blob?await uploadFile(capture.blob):null)):null;if(editor==='podcast'&&!audioKey)throw new Error('Сначала запишите или загрузите аудио');
   await api('library',{id:editing?.id,kind:editor,title,description,body,audioKey,duration:editing?.duration??capture.seconds,published});if(editor==='story'&&!editing){try{localStorage.removeItem('tt-story-draft');}catch{}}setEditor(null);setDirty(false);toast.success(published?'Опубликовано':'Черновик сохранён');setView(editor==='story'?'stories':'podcasts');await load();
  }catch(e){toast.error(errorText(e));}finally{setSaving(false);}
 }
 async function pickFile(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>80*1024*1024){toast.error('Максимум 80 МБ на запись');return;}await capture.accept(file);openEditor('podcast');setTitle(file.name.replace(/\.[^.]+$/,''));}
 async function startLive(){if(!liveTitle.trim()){toast.error('Укажите название эфира');return;}player.current?.pause();live.leave();const s=capture.stream.current??await capture.connect();if(s){await live.start(liveTitle,s);await refreshLive();await load();}}
 async function stopLive(){await run(()=>live.stop(),'Эфир завершён');capture.release();await refreshLive();}
 async function copyListenerLink(){try{await navigator.clipboard.writeText(location.origin+'/?mode=listen&view=live');toast.success('Ссылка слушателя скопирована');}catch{toast.error('Не удалось скопировать ссылку. Используй кнопку открытия слушателя.');}}
 function openLive(){
  setView('live');
  if(author)return;
  if(!liveStatus){void refreshLive();return;}
  if(live.joined&&live.activeId===liveStatus.id){
   if(live.phase==='paused'||live.phase==='blocked')void live.resume();
   return;
  }
  player.current?.pause();setPlaying(null);
  // Start within this click so the browser receives the listener's user gesture.
  void live.listen(liveStatus.id,liveStatus.title);
 }
 function playPost(p:Post){live.leave();setPlaying(p);setTimeout(()=>{player.current?.play().catch(()=>toast.info('Нажмите воспроизведение в плеере'));},50);}
 noticeHandler.current=async(raw:string)=>{const url=new URL(raw,location.origin);if(url.origin!==location.origin||url.pathname!=='/'||capture.recording||live.hosting)return;setAudience(true);setFilter('all');const v=url.searchParams.get('view');setView(['live','stories','settings'].includes(v??'')?v!:'podcasts');
  if(url.searchParams.has('post')){const fresh=await load(),p=fresh?.items.find(p=>p.id===url.searchParams.get('post'));if(p){if(p.kind==='podcast')playPost(p);else setReading(p);}else toast.info('Публикация больше недоступна');}
  if(url.searchParams.has('broadcast')){try{const r=await api<{live:Data['live']}>('live?status=1');setLiveNow(r.live);if(r.live?.id===url.searchParams.get('broadcast')){player.current?.pause();setPlaying(null);void live.listen(r.live.id,r.live.title);}else toast.info('Этот эфир уже завершён');}catch(e){toast.error(errorText(e));}}
 };
 const visible=(data?.items??[]).filter(p=>(author||p.published===1)&&(filter==='all'||p.published===(filter==='published'?1:0)));
 const count=(kind:string)=>(data?.items??[]).filter(p=>p.kind===kind&&(author||p.published===1)).length;
 const inputChoice=<InputPicker capture={capture} locked={capture.recording||!!live.hosting}/>;

 return <SidebarProvider><Toaster theme="dark" richColors position="top-center"/><Sidebar className="app-sidebar"><SidebarHeader className="brand-area"><Brand/><span className="side-caption">{author?'АВТОРСКАЯ СТУДИЯ':'ПОДКАСТЫ И ИСТОРИИ'}</span></SidebarHeader><SidebarContent><SidebarMenu className="nav-menu">{nav.filter(n=>author||data?.needsSetup||['podcasts','stories','live','settings'].includes(n.id)).map(n=><NavButton key={n.id} item={n} active={view===n.id} onClick={()=>{setView(n.id);setFilter('all');}}/>)}</SidebarMenu></SidebarContent><SidebarFooter className="side-footer"><div className="profile"><span className="avatar">{author?'Д':<img src="/brand/logo.png?v=0.4.1" width="38" height="38" alt=""/>}</span><div><strong>{author?'Дима':'True Thrills'}</strong><small>{author?'Автор канала':'Слушатель'}</small></div>{author&&<button className="quiet-button" aria-label="Выйти" title="Выйти" onClick={()=>void run(async()=>{await api('auth',{action:'logout'});location.href='/login';})}><LogOut size={17}/></button>}</div></SidebarFooter></Sidebar>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><img className="topbar-logo" src="/brand/logo.png?v=0.4.1" width="34" height="34" alt=""/><span>True Thrills</span><ChevronRight size={14}/><strong>{nav.find(n=>n.id===view)?.label}</strong></div><div className="top-actions"><span className="version-label">ВЕРСИЯ 0.5.0</span>{data?.isOwner&&!androidClient&&<button className="quiet-button" disabled={capture.recording} onClick={()=>{if(live.hosting){window.open('/?mode=listen&view=live','_blank','noopener,noreferrer');return;}capture.release();setAudience(!audience);setView(audience?'studio':liveStatus?'live':'podcasts');setFilter('all');void refreshLive();}}>{audience?<Monitor size={16}/>:<Eye size={16}/>}<span>{audience?'В студию':'Как слушатель'}</span></button>}</div></header>
 <main className={'main-content '+(!author?'listener-main':'')}>
 {error&&<div className="error-box" role="alert">{error}<button onClick={()=>void load()}>Повторить</button></div>}
 {!data&&!error&&<div className="loading-state"><Loader2 className="spin"/>Загружаем студию…</div>}
 {data?.needsSetup&&<section className="setup-card"><span className="eyebrow">TRUE THRILLS / ПЕРВЫЙ ЗАПУСК</span><h1>Твоя студия готова<br/>к первой записи.</h1><p>Закрепи студию за своим аккаунтом. Только ты сможешь публиковать выпуски, писать истории и запускать эфиры.</p>{data.signedIn?<button className="primary-button" onClick={()=>void setup()} disabled={saving}>Открыть мою студию<ArrowUpRight size={18}/></button>:<a className="primary-button" href="/login">Войти</a>}<small>Сейчас приложение доступно только тебе. Доступ для аудитории подключается отдельно.</small></section>}
 {data&&!data.needsSetup&&<>
 <div className="page-heading"><div><p className="eyebrow">{author?'TRUE THRILLS / WORKSPACE':'TRUE THRILLS / СЛУШАТЕЛЮ'}</p><h1>{view==='studio'?'Всё начинается с голоса.':view==='podcasts'?'Подкасты':view==='stories'?'Истории':view==='live'?'Прямой эфир':'Настройки'}</h1><p className="heading-description">{view==='studio'?'Запиши. Расскажи. Дай услышать.':view==='podcasts'?(author?'Твои выпуски — от черновика до публикации.':'Все опубликованные выпуски True Thrills.'):view==='stories'?(author?'Место для историй, которые ты хочешь рассказать.':'Истории True Thrills в текстовом формате.'):view==='live'?'Голос и слушатели. В реальном времени.':'Поддержка автора.'}</p></div>{author&&view==='podcasts'&&<button className="primary-button" onClick={()=>fileInput.current?.click()}><Upload size={17}/>Загрузить выпуск</button>}{author&&view==='stories'&&<button className="primary-button" onClick={()=>openEditor('story')}><Plus size={18}/>Написать историю</button>}</div>
 {liveError&&<div className="live-refresh-warning" role="status">Не удалось обновить статус эфира.<button onClick={()=>void refreshLive()}>Обновить</button></div>}
 {liveStatus&&view!=='live'&&<button type="button" className="onair-banner onair-notice" onClick={openLive}><span className="onair-symbol"><Radio size={25}/></span><span className="onair-copy"><span className="onair-label">{live.joined&&live.activeId===liveStatus.id&&live.listening?'ВЫ СЛУШАЕТЕ ЭФИР':'АВТОР В ПРЯМОМ ЭФИРЕ'}</span><strong>{liveStatus.title}</strong></span><span className="primary-button">{author?'Открыть эфир':live.joined&&live.activeId===liveStatus.id?(live.phase==='paused'?'Продолжить слушать':live.phase==='blocked'?'Включить звук':live.connecting||live.phase==='reconnecting'?'Подключаемся…':'Вернуться к эфиру'):'Слушать эфир'}<ChevronRight size={17}/></span></button>}
 {author&&live.hosting&&view!=='live'&&<div className="host-running-note">Микрофон включён · эфир продолжается<button onClick={()=>void stopLive()}>Завершить эфир</button></div>}
 {view==='studio'&&author&&<>
 <div className="studio-grid"><section className="recorder-panel"><div className="panel-heading"><span><Mic size={17}/>ЗАПИСЬ ПОДКАСТА</span><span className={capture.recording?'record-status active':'record-status'}><span className="led"/>{capture.recording?(capture.paused?'ПАУЗА':'REC'):capture.ready?'ГОТОВ К ЗАПИСИ':'ОЖИДАНИЕ'}</span></div>
 <div className="record-device-area">{inputChoice}</div><div className="recording-center"><div className="record-time">{clock(capture.seconds)}<span>.00</span></div><div className="waveform" aria-label="Уровень сигнала микрофона">{capture.samples.map((s,i)=><span key={i} style={{height:Math.max(3,Math.min(94,s*180+3))+'%'}}/>)}</div><div className="meter-labels"><span>−60</span><span>−36</span><span>−18</span><span>−6</span><span>0 dBFS</span></div><div className="peak-row"><span className="signal-label">{capture.ready?'ВХОДЯЩИЙ СИГНАЛ':'НЕТ СИГНАЛА'}</span><strong className={capture.level>-3?'clipping':''}>{capture.ready?Math.round(capture.level)+' dBFS':'— dBFS'}</strong></div></div>
 <div className="record-controls">{capture.recording?<><button className="primary-button" onClick={capture.stop}><Square size={16} fill="currentColor"/>Завершить запись</button><button className="icon-button" onClick={capture.pause} aria-label={capture.paused?'Продолжить':'Пауза'}>{capture.paused?<Play size={18}/>:<Pause size={18}/>}</button></>:<><button className="primary-button record-button" disabled={capture.busy||!!live.hosting} onClick={()=>capture.blob?setReplaceRecording(true):void capture.start()}><span className="record-dot"/>{capture.blob?'Новая запись':'Начать запись'}</button><button className="secondary-button" disabled={!!live.hosting||capture.busy} onClick={()=>fileInput.current?.click()}><Upload size={17}/>Загрузить аудио</button></>}</div>
 <div className="recorder-bottom"><AudioControls capture={capture}/><div className="input-help"><span>Проверь волну и уровень голоса перед записью.</span><button disabled={capture.busy||capture.recording||!!live.hosting} onClick={()=>capture.ready?capture.release():void capture.connect()}>{capture.busy?'Подключение…':capture.ready?'Отключить вход':'Проверить вход'}<Volume2 size={15}/></button></div></div>
 </section><aside className="studio-aside"><section className="live-card"><div className="live-card-top"><Radio size={23}/><span className="outline-tag">LIVE</span></div><h2>Ближе к слушателям.</h2><p>Выйди в эфир и расскажи историю своим голосом.</p><button className="secondary-button" disabled={capture.recording} onClick={()=>setView('live')}>Подготовить эфир<ArrowUpRight size={17}/></button><span className="card-footnote">Пилот: до 8 слушателей</span></section><section className="quick-story"><BookOpen size={22}/><div><h3>Есть что рассказать?</h3><p>Создай текстовую историю.</p></div><button className="round-button" aria-label="Написать историю" onClick={()=>openEditor('story')}><Plus size={22}/></button></section></aside></div>
 {capture.blob&&<section className="draft-bar"><span className="draft-icon"><FileAudio/></span><div className="draft-info"><strong>Последняя запись</strong><span>Черновик на этом устройстве · {(capture.blob.size/1024/1024).toFixed(1)} МБ</span></div><audio controls src={capture.url} preload="metadata"/><a className="quiet-button" href={capture.url} download={'True-Thrills.'+(capture.blob.type.includes('mp4')?'m4a':capture.blob instanceof File?capture.blob.name.split('.').pop():'webm')}><Download size={18}/><span>Скачать</span></a><button className="secondary-button" disabled={capture.busy} onClick={()=>openEditor('podcast')}>{capture.busy?'Подготавливаем запись…':'Оформить выпуск'}<ChevronRight size={16}/></button></section>}
 <div className="library-heading"><h2>Твоя библиотека</h2><span>Контент, который остаётся.</span></div><div className="library-tiles"><button onClick={()=>setView('podcasts')}><span className="tile-icon"><Headphones/></span><div><strong>{count('podcast')}</strong><span>Подкасты</span></div><ChevronRight/></button><button onClick={()=>setView('stories')}><span className="tile-icon"><BookOpen/></span><div><strong>{count('story')}</strong><span>Истории</span></div><ChevronRight/></button><button onClick={()=>setView('settings')}><span className="tile-icon"><Heart/></span><div><strong className="tile-word">Поддержка</strong><span>{data.donation?'Ссылка подключена':'Добавить ссылку для донатов'}</span></div><ChevronRight/></button></div>
 <div className="studio-note"><Headphones size={17}/><span>{capture.mode==='daw'?'Для контроля FL Studio: наушники в Komplete, INPUT/HOST к HOST; прослушивание CABLE Output — в Komplete 1/2.':'Для контроля голоса используй наушники и Direct Monitor аудиоинтерфейса.'}</span><span className="mono-label">{capture.channel==='stereo'?'STEREO / MIX':'MONO / VOICE'}</span></div>
 </>}
 {(view==='podcasts'||view==='stories')&&<>
 {author&&<Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">Все</TabsTrigger><TabsTrigger value="published">Опубликовано</TabsTrigger><TabsTrigger value="draft">Черновики</TabsTrigger></TabsList></Tabs>}
 {visible.filter(p=>p.kind===(view==='podcasts'?'podcast':'story')).length===0?<section className="empty-state"><span className="empty-icon">{view==='podcasts'?<Headphones size={36}/>:<BookOpen size={36}/>}</span><h2>{filter==='all'?(view==='podcasts'?'Здесь появится первый выпуск':'Здесь появится первая история'):'В этом разделе пока пусто'}</h2><p>{author?(view==='podcasts'?'Запиши подкаст в студии или загрузи готовое аудио.':'Напиши историю и опубликуй её для слушателей.'):'Автор ещё не добавил публикации в этот раздел.'}</p>{author&&<button className="secondary-button" onClick={()=>view==='podcasts'?setView('studio'):openEditor('story')}><Plus size={17}/>{view==='podcasts'?'В студию':'Написать историю'}</button>}</section>:<div className="post-list">{visible.filter(p=>p.kind===(view==='podcasts'?'podcast':'story')).map((p,i)=><article className="post-card" key={p.id}><button className={'post-cover '+(p.kind==='story'?'story-cover':'')} onClick={()=>p.kind==='podcast'?playPost(p):setReading(p)} aria-label={p.kind==='podcast'?'Слушать '+p.title:'Читать '+p.title}>{p.kind==='podcast'?<img className="post-logo" src="/brand/logo.png?v=0.4.1" width="76" height="76" alt=""/>:<BookOpen size={34}/>}<span>{String(i+1).padStart(2,'0')}</span></button><div className="post-content"><div className="post-meta">{p.kind==='podcast'?'ПОДКАСТ':'ИСТОРИЯ'}<span>·</span>{new Date(p.createdAt).toLocaleDateString('ru-RU')}{author&&<span className={'publish-tag '+(p.published?'published':'')}>{p.published?'Опубликовано':'Черновик'}</span>}</div><button className="post-title" onClick={()=>p.kind==='podcast'?playPost(p):setReading(p)}>{p.title}</button><p>{p.description||(p.kind==='story'?p.body.slice(0,130):'Аудиовыпуск True Thrills')}</p><div className="post-actions"><button className="text-button" onClick={()=>p.kind==='podcast'?playPost(p):setReading(p)}>{p.kind==='podcast'?<Play size={15}/>:<BookOpen size={15}/>} {p.kind==='podcast'?'Слушать':'Читать'}{p.duration>0&&<span>{clock(p.duration)}</span>}</button>{author&&<><button aria-label="Редактировать" onClick={()=>openEditor(p.kind as 'podcast'|'story',p)}><Pencil size={16}/></button><button aria-label={p.published?'Снять с публикации':'Опубликовать'} onClick={()=>void run(()=>api('library',{action:'visibility',id:p.id,published:!p.published}),p.published?'Перемещено в черновики':'Опубликовано')}>{p.published?<EyeOff size={16}/>:<Eye size={16}/>}</button><button aria-label="Удалить" onClick={()=>setConfirmDelete(p)}><Trash2 size={16}/></button></>}</div></div></article>)}</div>}
 {!author&&data.donation&&<a className="donation-banner" href={data.donation} target="_blank" rel="noopener noreferrer"><Heart/><div><strong>Поддержать True Thrills</strong><span>Твоя поддержка помогает выходить новым историям.</span></div><ArrowUpRight/></a>}
 </>}
 {view==='live'&&<div className="live-layout"><section className="live-main-panel live-console">
 {author?<>
 <div className={'session-status '+(live.hosting?'is-onair':'')} role="status"><Radio size={21}/><div><strong>{live.hosting?'Эфир идёт':live.connecting?'Запускаем эфир…':'Подготовка эфира'}</strong><span>{live.hostStatus||(capture.ready?'Микрофон готов. Можно проверить голос.':'Сначала выбери источник звука.')}</span></div>{live.hosting&&<span className="live-timer">{clock(live.hostSeconds)}</span>}</div>
 <label className="field">Название эфира<input maxLength={160} value={liveTitle} disabled={!!live.hosting} placeholder="О чём сегодня расскажешь?" onChange={e=>setLiveTitle(e.target.value)}/></label>
 {inputChoice}
 <SignalMeter samples={capture.samples} level={capture.level} active={capture.ready&&!capture.muted} label={capture.muted?'МИКРОФОН ВЫКЛЮЧЕН':live.hosting?'СИГНАЛ В ЭФИРЕ':'ПРОВЕРКА ГОЛОСА'}/>
 <AudioControls capture={capture}/>
 {live.hosting?<><div className="broadcast-summary"><Headphones size={20}/><strong>{live.listeners}</strong><span>{live.listeners?'подключено слушателей':'Ждём первого слушателя'}</span></div><div className="listener-link-actions"><a className="secondary-button" href="/?mode=listen&view=live" target="_blank" rel="noopener noreferrer"><Eye size={17}/>Открыть слушателя</a><button className="quiet-button" onClick={()=>void copyListenerLink()}>Скопировать ссылку</button></div><button className="primary-button stop-live-button" onClick={()=>void stopLive()}><Square size={17}/>Завершить эфир</button></>:<div className="preflight-actions"><button className="secondary-button" disabled={capture.busy||live.connecting||capture.recording} onClick={()=>capture.ready?capture.release():void capture.connect()}><Volume2 size={17}/>{capture.busy?'Подключаем…':capture.ready?'Отключить проверку':'Проверить микрофон'}</button><button className="primary-button" disabled={live.connecting||capture.recording||capture.busy||capture.discovering} onClick={()=>void startLive()}>{live.connecting?<Loader2 className="spin" size={18}/>:<Radio size={18}/>}Начать эфир</button></div>}
 {liveStatus&&!live.hosting&&<button className="quiet-button" onClick={()=>void run(async()=>{await api('live',{action:'stop',id:liveStatus!.id});await refreshLive();},'Эфир завершён')}>Завершить эфир из другого окна</button>}
 </>:<>
 <div className={'session-status '+(live.phase==='playing'?'is-onair':'')} role="status"><Headphones size={25}/><div><strong>{live.phase==='playing'?'Вы слушаете эфир':live.phase==='paused'?'На паузе':live.phase==='reconnecting'?'Восстанавливаем связь':live.phase==='connecting'||live.phase==='waiting'?'Подключение':live.phase==='blocked'?'Нужно включить звук':live.phase==='error'?'Не удалось подключиться':live.phase==='ended'?'Эфир завершён':liveStatus?'Автор в эфире':'Сейчас эфира нет'}</strong><span>{live.status||(liveStatus?'Нажми «Слушать эфир», чтобы подключиться.':'Когда автор начнёт эфир, он появится здесь.')}</span></div></div>
 <h2>{liveStatus?.title??'True Thrills Live'}</h2>
 <div className="listener-playback-actions">{live.joined?<>{live.listening?<button className="primary-button" onClick={live.pause}><Pause size={20}/>Пауза</button>:live.phase==='paused'||live.phase==='blocked'?<button className="primary-button" onClick={()=>void live.resume()}><Play size={20}/>{live.phase==='blocked'?'Включить звук':'Продолжить слушать'}</button>:<button className="primary-button" disabled aria-busy="true"><Loader2 className="spin" size={20}/>{live.phase==='reconnecting'?'Восстанавливаем связь…':'Подключаемся…'}</button>}<button className="quiet-button" onClick={live.leave}>{live.connecting||live.phase==='waiting'||live.phase==='reconnecting'?'Отменить':'Выйти из эфира'}</button></>:liveStatus?<button className="primary-button" onClick={openLive}><Headphones size={20}/>{live.phase==='error'?'Попробовать ещё раз':'Слушать эфир'}</button>:<button className="secondary-button" onClick={()=>void refreshLive()}>Проверить эфир</button>}</div>
 <SignalMeter samples={live.samples} level={live.level} active={live.listening} simple label="Звук эфира"/>
 {live.listening&&<div className="receiving-status">{live.volume===0?'Громкость выключена':live.level>-55?'Звук поступает':'Соединение есть · сейчас тихо'}</div>}
 <div className="listener-volume"><label htmlFor="live-volume"><Volume2 size={18}/>Громкость<span>{live.volume}%</span></label><Slider id="live-volume" aria-label="Громкость эфира" value={[live.volume]} min={0} max={100} step={1} onValueChange={v=>live.setVolume(v[0])}/></div>

 </>}
 </section><aside className="live-info"><h3>{author?'Контроль эфира':'Прослушивание'}</h3>{author?<><p><Mic size={18}/>Проверь волну до начала эфира. Список микрофонов доступен без записи.</p><p><Volume2 size={18}/>Усиление и выключение микрофона работают во время эфира.</p><p><Headphones size={18}/>Для проверки на втором устройстве используй наушники.</p></>:<><p><Headphones size={18}/>Нажми «Слушать эфир» — звук включится после подключения.</p><p><Volume2 size={18}/>Громкость можно изменить здесь или кнопками телефона.</p></>}{author&&<div className="pilot-note"><strong>Тестовая трансляция</strong><p>До 8 слушателей. В некоторых мобильных сетях прямое подключение может не установиться. Для проверки используй общий Wi-Fi.</p>{author&&<p>Эфир пока не записывается автоматически.</p>}</div>}{!author&&live.phase==='error'&&<p>Если подключение не получается, попробуй другую сеть Wi-Fi.</p>}</aside></div>}
 {view==='settings'&&<div className="settings-grid"><NotificationSettings/>{author&&<section className="settings-panel"><div className="section-icon"><Heart size={22}/></div><h2>Поддержка автора</h2><p>Добавь готовую платёжную ссылку своего сервиса донатов. Слушатель перейдёт на его защищённую страницу оплаты.</p><label className="field">Ссылка для донатов<input type="url" value={donation} onChange={e=>setDonation(e.target.value)} placeholder="https://…"/></label><button className="primary-button" onClick={()=>void run(()=>api('library',{action:'donation',url:donation}),'Ссылка сохранена')}><Check size={17}/>Сохранить ссылку</button><small>Платежи обрабатывает выбранный сервис. Приложение не хранит данные карт.</small></section>}</div>}
 </>}
 <footer className="content-footer"><span>TRUE THRILLS<span className="brand-point">.</span></span><span>Твоя история. Твой голос.</span></footer>
 </main></div>
 <input type="file" accept="audio/*,.mp3,.wav,.m4a,.webm,.ogg,.flac" ref={fileInput} onChange={pickFile} hidden/>
 {playing&&<PodcastPlayer key={playing.id} src={'/api/audio?id='+playing.id} title={playing.title} duration={playing.duration} audioRef={player} onClose={()=>{player.current?.pause();setPlaying(null);}}/>}
 <Dialog open={!!editor} onOpenChange={o=>{if(!o&&!saving){setEditor(null);}}}><DialogContent className="editor-dialog" onInteractOutside={e=>{if(dirty||saving)e.preventDefault();}} onEscapeKeyDown={e=>{if(dirty||saving)e.preventDefault();}} showCloseButton={!saving&&!dirty}><DialogHeader><DialogTitle>{editing?'Редактирование':editor==='story'?'Новая история':'Оформить подкаст'}</DialogTitle><DialogDescription>{editor==='story'?'Сохрани черновик или опубликуй историю.':'Добавь название и описание выпуска.'}</DialogDescription></DialogHeader><label className="field">Название<input value={title} maxLength={160} onChange={e=>{setTitle(e.target.value);setDirty(true);}} placeholder={editor==='story'?'Название истории':'Название выпуска'}/></label><label className="field">Короткое описание<textarea value={description} maxLength={2000} rows={2} onChange={e=>{setDescription(e.target.value);setDirty(true);}} placeholder="Несколько слов для слушателя"/></label>{editor==='story'?<label className="field">Текст истории<textarea className="story-textarea" value={body} maxLength={150000} rows={10} onChange={e=>{setBody(e.target.value);setDirty(true);}} placeholder="Начни рассказывать…"/></label>:<div className="audio-editor-preview"><FileAudio size={22}/><span>{editing?'Аудио выпуска':capture.blob?`${(capture.blob.size/1024/1024).toFixed(1)} МБ · готово к загрузке`:'Аудио не выбрано'}</span>{!editing&&capture.url&&<audio controls src={capture.url}/>}</div>}<div className="editor-actions"><button className="quiet-button" disabled={saving} onClick={()=>{if(dirty){setDiscardText(true);}else setEditor(null);}}>Отмена</button><button className="secondary-button" disabled={saving} onClick={()=>void save(false)}>В черновики</button><button className="primary-button" disabled={saving} onClick={()=>void save(true)}>{saving?<Loader2 className="spin" size={17}/>:<ArrowUpRight size={17}/>} {saving?'Сохраняем…':'Опубликовать'}</button></div></DialogContent></Dialog>
 <Dialog open={!!reading} onOpenChange={o=>{if(!o)setReading(null);}}><DialogContent className="reading-dialog"><DialogHeader><DialogDescription>TRUE THRILLS / ИСТОРИЯ</DialogDescription><DialogTitle>{reading?.title}</DialogTitle></DialogHeader>{reading?.description&&<p className="reading-intro">{reading.description}</p>}<div className="reading-body">{reading?.body}</div></DialogContent></Dialog>
 <AlertDialog open={!!confirmDelete} onOpenChange={o=>{if(!o)setConfirmDelete(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Удалить «{confirmDelete?.title}»?</AlertDialogTitle><AlertDialogDescription>Публикация и её аудиозапись будут удалены. Это действие нельзя отменить.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction onClick={()=>void run(()=>api('library',{action:'delete',id:confirmDelete?.id}),'Удалено')}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={discardText} onOpenChange={setDiscardText}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Закрыть без сохранения?</AlertDialogTitle><AlertDialogDescription>Изменения текста не будут сохранены.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Продолжить редактирование</AlertDialogCancel><AlertDialogAction onClick={()=>{setEditor(null);setDirty(false);}}>Закрыть</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={replaceRecording} onOpenChange={setReplaceRecording}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Начать новую запись?</AlertDialogTitle><AlertDialogDescription>Новая запись заменит локальный аудиочерновик. Сначала скачай или опубликуй предыдущую запись, если она нужна.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction onClick={()=>void capture.start()}>Начать запись</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
