'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Mic,Radio,BookOpen,Headphones,Settings,Download,ArrowUpRight,Plus,Upload,Square,Pause,Play,Heart,Check,Volume2,FileAudio,ChevronRight,Monitor,Trash2,Eye,EyeOff,Pencil,Loader2,LogOut,LogIn,Share2,Video,Music2,Camera,Send,MessageCircle,Globe,Link2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {useCapture} from '@/hooks/use-capture';
import {useLive} from '@/hooks/use-live';
import {PodcastPlayer} from '@/components/studio/podcast-player';
import {InputPicker,SignalMeter,AudioControls} from '@/components/studio/audio-console';
import {NotificationSettings} from '@/components/studio/notification-settings';
import {LanguageSettings} from '@/components/studio/language-settings';
import {Slider} from '@/components/ui/slider';
import {api,clock,errorText} from '@/lib/client';
import {VideoFrame} from '@/components/studio/video-player';
import {YoutubeIcon} from '@/components/studio/brand-icons';
import {SOCIALS,type SocialKind,type SocialLink} from '@/lib/video';
import {useT} from '@/components/i18n-provider';

type Post={id:string;kind:string;title:string;description:string;body:string;audioKey:string|null;videoUrl:string|null;duration:number;published:number;createdAt:number};
type Data={items:Post[];isOwner:boolean;needsSetup:boolean;signedIn:boolean;donation:string;links:SocialLink[];live:{id:string;title:string}|null};
const SOCIAL_ICON:Record<SocialKind,React.ComponentType<{size?:number}>>={youtube:YoutubeIcon,tiktok:Music2,instagram:Camera,telegram:Send,vk:MessageCircle,site:Globe};
const LISTEN_VIEWS=['home','podcasts','videos','stories','live','settings'];
export default function Studio(){
 const {t,tag}=useT();
 const noticeHandler=useRef<(url:string)=>Promise<void>>(async()=>{});
 const [discardText,setDiscardText]=useState(false);
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[view,setView]=useState('home'),[audience,setAudience]=useState(false),[androidClient,setAndroidClient]=useState(false);
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[body,setBody]=useState(''),[editing,setEditing]=useState<Post|null>(null),[editor,setEditor]=useState<'story'|'podcast'|'video'|null>(null),[saving,setSaving]=useState(false),[donation,setDonation]=useState(''),[linkDraft,setLinkDraft]=useState<Record<string,string>>({}),[videoUrl,setVideoUrl]=useState(''),[watching,setWatching]=useState<Post|null>(null),[liveTitle,setLiveTitle]=useState(''),[filter,setFilter]=useState('all'),[reading,setReading]=useState<Post|null>(null),[playing,setPlaying]=useState<Post|null>(null),[confirmDelete,setConfirmDelete]=useState<Post|null>(null),[dirty,setDirty]=useState(false),[replaceRecording,setReplaceRecording]=useState(false);
 const capture=useCapture(),live=useLive(),player=useRef<HTMLAudioElement|null>(null),fileInput=useRef<HTMLInputElement|null>(null);
 const author=!!data?.isOwner&&!audience;
 useEffect(()=>{const native=window as Window & {chrome?:{webview?:{postMessage:(message:string)=>void}}};native.chrome?.webview?.postMessage(capture.recording||!!live.hosting?'true-thrills:active':'true-thrills:idle');},[capture.recording,live.hosting]);
 const [liveNow,setLiveNow]=useState<Data['live']>(null),[liveError,setLiveError]=useState(false);
 const liveStatus=liveNow;
 const liveRequest=useRef(false);
 const refreshLive=useCallback(async()=>{if(liveRequest.current)return;liveRequest.current=true;try{const r=await api<{live:Data['live']}>('live?status=1');setLiveNow(r.live);setLiveError(false);}catch{setLiveError(true);}finally{liveRequest.current=false;}},[]);
 useEffect(()=>{void refreshLive();const timer=setInterval(()=>void refreshLive(),3000);const resume=()=>{if(document.visibilityState==='visible')void refreshLive();};document.addEventListener('visibilitychange',resume);window.addEventListener('focus',resume);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',resume);window.removeEventListener('focus',resume);};},[refreshLive]);
 useEffect(()=>{if(live.hosting&&!capture.ready){void live.stop().catch(()=>{});toast.error(t('live.micLost'));}},[capture.ready,live.hosting]);
 const load=useCallback(async()=>{try{const d=await api<Data>('library');setData(d);setError('');return d as Data;}catch(e){setError(errorText(e));return null;}},[]);
 useEffect(()=>{load().then(d=>{if(d){setDonation(d.donation);setLinkDraft(Object.fromEntries((d.links??[]).map(l=>[l.kind,l.url])));const q=new URLSearchParams(location.search);setAndroidClient(q.get('client')==='android');if(q.get('mode')==='listen'){setAudience(true);setView(LISTEN_VIEWS.includes(q.get('view')??'')?q.get('view')!:'home');}else if(!d.isOwner&&!d.needsSetup)setView('home');if(q.has('post')||q.has('broadcast'))void noticeHandler.current(location.href);}});const timer=setInterval(()=>void load(),15000);return()=>clearInterval(timer);},[load]);
 useEffect(()=>{if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{});const handler=(e:MessageEvent)=>{if(e.data?.type==='tt-notification'&&typeof e.data.url==='string')void noticeHandler.current(e.data.url);};navigator.serviceWorker.addEventListener('message',handler);return()=>navigator.serviceWorker.removeEventListener('message',handler);},[]);

 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||saving){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,saving]);
 useEffect(()=>{if(editor==='story'&&!editing){try{localStorage.setItem('tt-story-draft',JSON.stringify({title,description,body}));}catch{}}},[editor,editing,title,description,body]);
 const run=async(fn:()=>Promise<unknown>,message?:string)=>{try{await fn();if(message)toast.success(message);await load();}catch(e){toast.error(errorText(e));}};
 function openEditor(kind:'story'|'podcast'|'video',p?:Post){setEditing(p??null);setTitle(p?.title??'');setDescription(p?.description??'');setBody(p?.body??'');setVideoUrl(p?.videoUrl??'');setDirty(false);setEditor(kind);if(kind==='story'&&!p){try{const saved=JSON.parse(localStorage.getItem('tt-story-draft')||'null');if(saved){setTitle(saved.title||'');setBody(saved.body||'');setDescription(saved.description||'');}}catch{}}}
 async function setup(){setSaving(true);await run(async()=>{await api('library',{action:'setup'});setView('home');},t('studio.ready0'));setSaving(false);}
 async function uploadFile(b:Blob){if(!b.size)throw new Error(t('capture.emptyFile'));if(b.size>80*1024*1024)throw new Error(t('capture.tooBigUpload'));let mime=b.type||'audio/mpeg';if(mime==='video/webm')mime='audio/webm';if(mime==='audio/x-m4a')mime='audio/mp4';const r=await fetch('/api/audio',{method:'POST',headers:{'Content-Type':mime,'X-Upload-Size':String(b.size)},body:b});const d=await r.json() as {error?:string;key:string};if(!r.ok)throw new Error(d.error?t(d.error.replace(/^#/,'')):t('capture.uploadFailed'));return d.key as string;}
 async function save(published:boolean){
  if(!title.trim()){toast.error(t('editor.needTitle'));return;}if(editor==='story'&&!body.trim()){toast.error(t('editor.needStory'));return;}if(editor==='video'&&!videoUrl.trim()){toast.error(t('editor.needVideoUrl'));return;}setSaving(true);
  try{const audioKey=editor==='podcast'?(editing?.audioKey??(capture.blob?await uploadFile(capture.blob):null)):null;if(editor==='podcast'&&!audioKey)throw new Error(t('editor.needAudio'));
   await api('library',{id:editing?.id,kind:editor,title,description,body,videoUrl,audioKey,duration:editing?.duration??capture.seconds,published});if(editor==='story'&&!editing){try{localStorage.removeItem('tt-story-draft');}catch{}}setEditor(null);setDirty(false);toast.success(published?t('editor.publishedToast'):t('editor.draftSaved'));setView(editor==='story'?'stories':editor==='video'?'videos':'podcasts');await load();
  }catch(e){toast.error(errorText(e));}finally{setSaving(false);}
 }
 async function pickFile(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>80*1024*1024){toast.error(t('capture.tooBigUpload'));return;}await capture.accept(file);openEditor('podcast');setTitle(file.name.replace(/\.[^.]+$/,''));}
 async function startLive(){if(!liveTitle.trim()){toast.error(t('live.titleRequired'));return;}player.current?.pause();live.leave();const s=capture.stream.current??await capture.connect();if(s){await live.start(liveTitle,s);await refreshLive();await load();}}
 async function stopLive(){await run(()=>live.stop(),t('live.stopped'));capture.release();await refreshLive();}
 async function copyListenerLink(){try{await navigator.clipboard.writeText(location.origin+'/?mode=listen&view=live');toast.success(t('live.linkCopied'));}catch{toast.error(t('live.linkCopyFailed'));}}
 async function copyChannelLink(){try{await navigator.clipboard.writeText(location.origin+'/?mode=listen&view=home');toast.success(t('settings.channelLinkCopied'));}catch{toast.error(t('settings.channelLinkFailed'));}}
 function openLive(){
  setView('live');
  if(author)return;
  if(!liveStatus){void refreshLive();return;}
  if(live.joined&&live.activeId===liveStatus.id){
   if(live.phase==='paused'||live.phase==='blocked')void live.resume();
   return;
  }
  player.current?.pause();setPlaying(null);
  // Start within this click so the browser receives the listener's user gesture.
  void live.listen(liveStatus.id,liveStatus.title);
 }
 function playPost(p:Post){live.leave();setPlaying(p);setTimeout(()=>{player.current?.play().catch(()=>toast.info(t('player.tapInPlayer')));},50);}
 // Видео и подкаст не должны звучать одновременно, поэтому открытие видео
 // останавливает аудиоплеер и выходит из эфира.
 function openPost(p:Post){if(p.kind==='podcast'){playPost(p);return;}if(p.kind==='video'){player.current?.pause();setPlaying(null);live.leave();setWatching(p);return;}setReading(p);}
 noticeHandler.current=async(raw:string)=>{const url=new URL(raw,location.origin);if(url.origin!==location.origin||url.pathname!=='/'||capture.recording||live.hosting)return;setAudience(true);setFilter('all');const v=url.searchParams.get('view');setView(LISTEN_VIEWS.includes(v??'')?v!:'home');
  if(url.searchParams.has('post')){const fresh=await load(),p=fresh?.items.find(p=>p.id===url.searchParams.get('post'));if(p)openPost(p);else toast.info(t('post.gone'));}
  if(url.searchParams.has('broadcast')){try{const r=await api<{live:Data['live']}>('live?status=1');setLiveNow(r.live);if(r.live?.id===url.searchParams.get('broadcast')){player.current?.pause();setPlaying(null);void live.listen(r.live.id,r.live.title);}else toast.info(t('live.alreadyEnded'));}catch(e){toast.error(errorText(e));}}
 };
 const visible=(data?.items??[]).filter(p=>(author||p.published===1)&&(filter==='all'||p.published===(filter==='published'?1:0)));
 const count=(kind:string)=>(data?.items??[]).filter(p=>p.kind===kind&&(author||p.published===1)).length;
 const inputChoice=<InputPicker capture={capture} locked={capture.recording||!!live.hosting}/>;
 const goto=(v:string)=>{setView(v);setFilter('all');};
 const listKind=view==='podcasts'?'podcast':view==='videos'?'video':'story';
 const listed=visible.filter(p=>p.kind===listKind);
 const socialRow=data?.links?.length?<div className="social-row">{data.links.map(l=>{const Icon=SOCIAL_ICON[l.kind]??Globe;return <a key={l.kind+l.url} className="social-chip" href={l.url} target="_blank" rel="noopener noreferrer"><Icon size={16}/>{t(SOCIALS.find(s=>s.kind===l.kind)?.labelKey??'common.link')}</a>;})}</div>:null;
 const supportCard=data?.donation?<a className="support-card" href={data.donation} target="_blank" rel="noopener noreferrer"><span className="support-icon"><Heart size={22}/></span><span className="support-copy"><strong>{t('support.title')}</strong><span>{t('support.subtitle')}</span></span><ArrowUpRight size={19}/></a>:null;

 return <>
 <Toaster theme="dark" richColors position="top-center"/>
 <div className="app-shell">
 <header className="top-header">
  <div className="top-header-brand"><img src="/brand/logo.png?v=0.4.1" width="44" height="44" alt=""/><span>True Thrills</span></div>
  <div className="top-header-actions">
   {!!data?.donation&&<a className="support-button" href={data.donation} target="_blank" rel="noopener noreferrer"><Heart size={15}/><span>{t('header.support')}</span></a>}
   {data&&!data.needsSetup&&<button className="quiet-button" aria-label={t('header.settings')} title={t('header.settings')} onClick={()=>goto('settings')}><Settings size={18}/></button>}
   {data?.isOwner&&!androidClient&&<button className="quiet-button" aria-label={audience?t('header.toStudio'):t('header.asListener')} title={audience?t('header.toStudio'):t('header.asListener')} disabled={capture.recording} onClick={()=>{if(live.hosting){window.open('/?mode=listen&view=live','_blank','noopener,noreferrer');return;}capture.release();setAudience(!audience);setView(audience?'home':liveStatus?'live':'podcasts');setFilter('all');void refreshLive();}}>{audience?<Monitor size={18}/>:<Eye size={18}/>}</button>}
   {author?<button className="quiet-button" aria-label={t('header.logout')} title={t('header.logout')} onClick={()=>void run(async()=>{await api('auth',{action:'logout'});location.href='/login';})}><LogOut size={18}/></button>:<a className="quiet-button" aria-label={t('header.loginAuthor')} title={t('header.loginAuthor')} href="/login"><LogIn size={18}/></a>}
  </div>
 </header>
 <main className={'main-content '+(!author?'listener-main':'')}>
 {error&&<div className="error-box" role="alert">{error}<button onClick={()=>void load()}>{t('common.retry')}</button></div>}
 {!data&&!error&&<div className="loading-state"><Loader2 className="spin"/>{t('common.loading')}</div>}
 {data?.needsSetup&&<section className="setup-card"><span className="eyebrow">{t('setup.eyebrow')}</span><h1 className="wrap-lines">{t('setup.title')}</h1><p>{t('setup.text')}</p>{data.signedIn?<button className="primary-button" onClick={()=>void setup()} disabled={saving}>{t('setup.cta')}<ArrowUpRight size={18}/></button>:<a className="primary-button" href="/login">{t('common.login')}</a>}<small>{t('setup.note')}</small></section>}
 {data&&!data.needsSetup&&<>
 <div className="page-heading"><div><p className="eyebrow">{author?t('heading.eyebrowAuthor'):t('heading.eyebrowListener')}</p><h1>{view==='home'?(author?t('heading.homeAuthor'):t('heading.homeListener')):view==='studio'?t('heading.studio'):view==='podcasts'?t('heading.podcasts'):view==='videos'?t('heading.videos'):view==='stories'?t('heading.stories'):view==='live'?t('heading.live'):t('heading.settings')}</h1><p className="heading-description">{view==='home'?(author?t('desc.homeAuthor'):t('desc.homeListener')):view==='studio'?t('desc.studio'):view==='podcasts'?(author?t('desc.podcastsAuthor'):t('desc.podcastsListener')):view==='videos'?(author?t('desc.videosAuthor'):t('desc.videosListener')):view==='stories'?(author?t('desc.storiesAuthor'):t('desc.storiesListener')):view==='live'?t('desc.live'):(author?t('desc.settingsAuthor'):t('desc.settingsListener'))}</p></div>{author&&view==='podcasts'&&<button className="primary-button" onClick={()=>fileInput.current?.click()}><Upload size={17}/>{t('studio.uploadEpisode')}</button>}{author&&view==='stories'&&<button className="primary-button" onClick={()=>openEditor('story')}><Plus size={18}/>{t('studio.newStory')}</button>}</div>
 {liveError&&<div className="live-refresh-warning" role="status">{t('live.refreshFailed')}<button onClick={()=>void refreshLive()}>{t('common.refresh')}</button></div>}
 {liveStatus&&view!=='live'&&<button type="button" className="onair-banner onair-notice" onClick={openLive}><span className="onair-symbol"><Radio size={25}/></span><span className="onair-copy"><span className="onair-label">{live.joined&&live.activeId===liveStatus.id&&live.listening?t('live.youAreListening'):t('live.authorOnAir')}</span><strong>{liveStatus.title}</strong></span><span className="primary-button">{author?t('live.open'):live.joined&&live.activeId===liveStatus.id?(live.phase==='paused'?t('live.continueListening'):live.phase==='blocked'?t('live.enableSound'):live.connecting||live.phase==='reconnecting'?t('live.connecting'):t('live.backToLive')):t('live.listen')}<ChevronRight size={17}/></span></button>}
 {author&&live.hosting&&view!=='live'&&<div className="host-running-note">{t('live.micOnNote')}<button onClick={()=>void stopLive()}>{t('live.stop')}</button></div>}
 {view==='home'&&author&&<div className="home-actions">
 <button className="home-tile" onClick={()=>goto('studio')}><Mic size={22}/><span>{t('home.record')}</span></button>
 <button className="home-tile" onClick={()=>openEditor('video')}><Video size={22}/><span>{t('home.addVideo')}</span></button>
 <button className="home-tile" onClick={()=>openEditor('story')}><BookOpen size={22}/><span>{t('home.writeStory')}</span></button>
 <button className="home-tile home-tile-live" onClick={()=>goto('live')}><Radio size={22}/><span>{t('home.startLive')}</span></button>
 <button className="home-tile" onClick={()=>void copyChannelLink()}><Share2 size={22}/><span>{t('home.shareChannel')}</span></button>
 </div>}
 {view==='home'&&author&&(supportCard??<button className="support-card support-setup" onClick={()=>goto('settings')}><span className="support-icon"><Heart size={22}/></span><span className="support-copy"><strong>{t('support.setupTitle')}</strong><span>{t('support.setupText')}</span></span><ChevronRight size={19}/></button>)}
 {view==='home'&&!author&&<>
 <div className="home-actions">
 <button className="home-tile" onClick={()=>goto('videos')}><Video size={22}/><span>{t('home.watchVideos')}</span></button>
 <button className="home-tile" onClick={()=>goto('podcasts')}><Headphones size={22}/><span>{t('home.listenPodcasts')}</span></button>
 <button className="home-tile" onClick={()=>goto('stories')}><BookOpen size={22}/><span>{t('home.readStories')}</span></button>
 <button className="home-tile home-tile-live" onClick={openLive}><Radio size={22}/><span>{t('home.liveNow')}</span></button>
 </div>
 {supportCard}
 {socialRow&&<div className="home-social"><span className="social-caption">{t('home.socialCaption')}</span>{socialRow}</div>}
 </>}
 {view==='studio'&&author&&<>
 <div className="studio-grid"><section className="recorder-panel"><div className="panel-heading"><span><Mic size={17}/>{t('studio.panelTitle')}</span><span className={capture.recording?'record-status active':'record-status'}><span className="led"/>{capture.recording?(capture.paused?t('studio.paused'):t('studio.rec')):capture.ready?t('studio.ready'):t('studio.waiting')}</span></div>
 <div className="record-device-area">{inputChoice}</div><div className="recording-center"><div className="record-time">{clock(capture.seconds)}<span>.00</span></div><div className="waveform" aria-label={t('studio.levelAria')}>{capture.samples.map((s,i)=><span key={i} style={{height:Math.max(3,Math.min(94,s*180+3))+'%'}}/>)}</div><div className="meter-labels"><span>−60</span><span>−36</span><span>−18</span><span>−6</span><span>0 dBFS</span></div><div className="peak-row"><span className="signal-label">{capture.ready?t('studio.incomingSignal'):t('studio.noSignal')}</span><strong className={capture.level>-3?'clipping':''}>{capture.ready?Math.round(capture.level)+' dBFS':'— dBFS'}</strong></div></div>
 <div className="record-controls">{capture.recording?<><button className="primary-button" onClick={capture.stop}><Square size={16} fill="currentColor"/>{t('studio.stopRecording')}</button><button className="icon-button" onClick={capture.pause} aria-label={capture.paused?t('studio.continue'):t('studio.pause')}>{capture.paused?<Play size={18}/>:<Pause size={18}/>}</button></>:<><button className="primary-button record-button" disabled={capture.busy||!!live.hosting} onClick={()=>capture.blob?setReplaceRecording(true):void capture.start()}><span className="record-dot"/>{capture.blob?t('studio.newRecording'):t('studio.startRecording')}</button><button className="secondary-button" disabled={!!live.hosting||capture.busy} onClick={()=>fileInput.current?.click()}><Upload size={17}/>{t('studio.uploadAudio')}</button></>}</div>
 <div className="recorder-bottom"><AudioControls capture={capture}/><div className="input-help"><span>{t('studio.checkTip')}</span><button disabled={capture.busy||capture.recording||!!live.hosting} onClick={()=>capture.ready?capture.release():void capture.connect()}>{capture.busy?t('studio.connecting'):capture.ready?t('studio.disconnectInput'):t('studio.checkInput')}<Volume2 size={15}/></button></div></div>
 </section><aside className="studio-aside"><section className="live-card"><div className="live-card-top"><Radio size={23}/><span className="outline-tag">LIVE</span></div><h2>{t('studio.liveCardTitle')}</h2><p>{t('studio.liveCardText')}</p><button className="secondary-button" disabled={capture.recording} onClick={()=>setView('live')}>{t('studio.prepareLive')}<ArrowUpRight size={17}/></button><span className="card-footnote">{t('studio.pilotFootnote')}</span></section><section className="quick-story"><BookOpen size={22}/><div><h3>{t('studio.quickStoryTitle')}</h3><p>{t('studio.quickStoryText')}</p></div><button className="round-button" aria-label={t('studio.writeStory')} onClick={()=>openEditor('story')}><Plus size={22}/></button></section></aside></div>
 {capture.blob&&<section className="draft-bar"><span className="draft-icon"><FileAudio/></span><div className="draft-info"><strong>{t('studio.lastRecording')}</strong><span>{t('studio.localDraft')} · {(capture.blob.size/1024/1024).toFixed(1)} {t('common.mb')}</span></div><audio controls src={capture.url} preload="metadata"/><a className="quiet-button" href={capture.url} download={'True-Thrills.'+(capture.blob.type.includes('mp4')?'m4a':capture.blob instanceof File?capture.blob.name.split('.').pop():'webm')}><Download size={18}/><span>{t('studio.download')}</span></a><button className="secondary-button" disabled={capture.busy} onClick={()=>openEditor('podcast')}>{capture.busy?t('studio.preparing'):t('studio.publishEpisode')}<ChevronRight size={16}/></button></section>}
 <div className="library-heading"><h2>{t('studio.libraryTitle')}</h2><span>{t('studio.librarySubtitle')}</span></div><div className="library-tiles"><button onClick={()=>setView('podcasts')}><span className="tile-icon"><Headphones/></span><div><strong>{count('podcast')}</strong><span>{t('nav.podcasts')}</span></div><ChevronRight/></button><button onClick={()=>setView('videos')}><span className="tile-icon"><Video/></span><div><strong>{count('video')}</strong><span>{t('nav.videos')}</span></div><ChevronRight/></button><button onClick={()=>setView('stories')}><span className="tile-icon"><BookOpen/></span><div><strong>{count('story')}</strong><span>{t('nav.stories')}</span></div><ChevronRight/></button><button onClick={()=>setView('settings')}><span className="tile-icon"><Heart/></span><div><strong className="tile-word">{t('studio.supportTile')}</strong><span>{data.donation?t('studio.donationSet'):t('studio.donationMissing')}</span></div><ChevronRight/></button></div>
 <div className="studio-note"><Headphones size={17}/><span>{capture.mode==='daw'?t('studio.monitorDaw'):t('studio.monitorMic')}</span><span className="mono-label">{capture.channel==='stereo'?'STEREO / MIX':'MONO / VOICE'}</span></div>
 </>}
 {(view==='podcasts'||view==='stories'||view==='videos')&&<>
 {author&&<Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">{t('filter.all')}</TabsTrigger><TabsTrigger value="published">{t('filter.published')}</TabsTrigger><TabsTrigger value="draft">{t('filter.drafts')}</TabsTrigger></TabsList></Tabs>}
 {listed.length===0?<section className="empty-state"><span className="empty-icon">{view==='podcasts'?<Headphones size={36}/>:view==='videos'?<Video size={36}/>:<BookOpen size={36}/>}</span><h2>{filter!=='all'?t('empty.sectionEmpty'):view==='podcasts'?t('empty.firstPodcast'):view==='videos'?t('empty.firstVideo'):t('empty.firstStory')}</h2><p>{!author?t('empty.listener'):view==='podcasts'?t('empty.podcastHint'):view==='videos'?t('empty.videoHint'):t('empty.storyHint')}</p>{author&&<button className="secondary-button" onClick={()=>view==='podcasts'?setView('studio'):openEditor(view==='videos'?'video':'story')}><Plus size={17}/>{view==='podcasts'?t('empty.toStudio'):view==='videos'?t('empty.addVideo'):t('studio.writeStory')}</button>}</section>:<div className="post-list">{listed.map((p,i)=><article className="post-card" key={p.id}><button className={'post-cover '+(p.kind==='story'?'story-cover':p.kind==='video'?'video-cover':'')} onClick={()=>openPost(p)} aria-label={t(p.kind==='podcast'?'post.listenAria':p.kind==='video'?'post.watchAria':'post.readAria',{title:p.title})}>{p.kind==='podcast'?<img className="post-logo" src="/brand/logo.png?v=0.4.1" width="76" height="76" alt=""/>:p.kind==='video'?<Play size={30}/>:<BookOpen size={34}/>}<span>{String(i+1).padStart(2,'0')}</span></button><div className="post-content"><div className="post-meta">{p.kind==='podcast'?t('post.podcast'):p.kind==='video'?t('post.video'):t('post.story')}<span>{new Date(p.createdAt).toLocaleDateString(tag)}</span>{author&&<span className={'publish-tag '+(p.published?'published':'')}>{p.published?t('post.published'):t('post.draft')}</span>}</div><button className="post-title" onClick={()=>openPost(p)}>{p.title}</button><p>{p.description||(p.kind==='story'?p.body.slice(0,130):p.kind==='video'?t('post.defaultVideo'):t('post.defaultPodcast'))}</p><div className="post-actions"><button className="text-button" onClick={()=>openPost(p)}>{p.kind==='podcast'?<Play size={15}/>:p.kind==='video'?<Video size={15}/>:<BookOpen size={15}/>} {p.kind==='podcast'?t('post.listen'):p.kind==='video'?t('post.watch'):t('post.read')}{p.duration>0&&<span>{clock(p.duration)}</span>}</button>{author&&<><button aria-label={t('post.edit')} onClick={()=>openEditor(p.kind as 'podcast'|'story'|'video',p)}><Pencil size={16}/></button><button aria-label={p.published?t('post.unpublish'):t('post.publish')} onClick={()=>void run(()=>api('library',{action:'visibility',id:p.id,published:!p.published}),p.published?t('post.movedToDrafts'):t('post.publishedToast'))}>{p.published?<EyeOff size={16}/>:<Eye size={16}/>}</button><button aria-label={t('post.delete')} onClick={()=>setConfirmDelete(p)}><Trash2 size={16}/></button></>}</div></div></article>)}</div>}
 {!author&&supportCard}
 </>}
 {view==='live'&&<div className="live-layout"><section className="live-main-panel live-console">
 {author?<>
 <div className={'session-status '+(live.hosting?'is-onair':'')} role="status"><Radio size={21}/><div><strong>{live.hosting?t('live.running'):live.connecting?t('live.starting'):t('live.preparing')}</strong><span>{live.hostStatus||(capture.ready?t('live.micReady'):t('live.pickSource'))}</span></div>{live.hosting&&<span className="live-timer">{clock(live.hostSeconds)}</span>}</div>
 <label className="field">{t('live.titleField')}<input maxLength={160} value={liveTitle} disabled={!!live.hosting} placeholder={t('live.titlePlaceholder')} onChange={e=>setLiveTitle(e.target.value)}/></label>
 {inputChoice}
 <SignalMeter samples={capture.samples} level={capture.level} active={capture.ready&&!capture.muted} label={capture.muted?t('live.micOff'):live.hosting?t('live.signalOnAir'):t('live.voiceCheck')}/>
 <AudioControls capture={capture}/>
 {live.hosting?<><div className="broadcast-summary"><Headphones size={20}/><strong>{live.listeners}</strong><span>{live.listeners?t('live.listenersConnected'):t('live.waitingFirst')}</span></div><div className="listener-link-actions"><a className="secondary-button" href="/?mode=listen&view=live" target="_blank" rel="noopener noreferrer"><Eye size={17}/>{t('live.openListener')}</a><button className="quiet-button" onClick={()=>void copyListenerLink()}>{t('live.copyLink')}</button></div><button className="primary-button stop-live-button" onClick={()=>void stopLive()}><Square size={17}/>{t('live.stop')}</button></>:<div className="preflight-actions"><button className="secondary-button" disabled={capture.busy||live.connecting||capture.recording} onClick={()=>capture.ready?capture.release():void capture.connect()}><Volume2 size={17}/>{capture.busy?t('live.connectingShort'):capture.ready?t('live.stopCheck'):t('live.checkMic')}</button><button className="primary-button" disabled={live.connecting||capture.recording||capture.busy||capture.discovering} onClick={()=>void startLive()}>{live.connecting?<Loader2 className="spin" size={18}/>:<Radio size={18}/>}{t('live.start')}</button></div>}
 {liveStatus&&!live.hosting&&<button className="quiet-button" onClick={()=>void run(async()=>{await api('live',{action:'stop',id:liveStatus!.id});await refreshLive();},t('live.stopped'))}>{t('live.stopFromOtherWindow')}</button>}
 </>:<>
 <div className={'session-status '+(live.phase==='playing'?'is-onair':'')} role="status"><Headphones size={25}/><div><strong>{live.phase==='playing'?t('live.listeningNow'):live.phase==='paused'?t('live.paused'):live.phase==='reconnecting'?t('live.reconnecting'):live.phase==='connecting'||live.phase==='waiting'?t('live.connectingState'):live.phase==='blocked'?t('live.needSound'):live.phase==='error'?t('live.connectFailed'):live.phase==='ended'?t('live.ended'):liveStatus?t('live.authorOnAirPlain'):t('live.noneNow')}</strong><span>{live.status||(liveStatus?t('live.tapToConnect'):t('live.willAppearHere'))}</span></div></div>
 <h2>{liveStatus?.title??'True Thrills Live'}</h2>
 <div className="listener-playback-actions">{live.joined?<>{live.listening?<button className="primary-button" onClick={live.pause}><Pause size={20}/>{t('live.pause')}</button>:live.phase==='paused'||live.phase==='blocked'?<button className="primary-button" onClick={()=>void live.resume()}><Play size={20}/>{live.phase==='blocked'?t('live.enableSound'):t('live.resume')}</button>:<button className="primary-button" disabled aria-busy="true"><Loader2 className="spin" size={20}/>{live.phase==='reconnecting'?t('live.reconnectingShort'):t('live.connecting')}</button>}<button className="quiet-button" onClick={live.leave}>{live.connecting||live.phase==='waiting'||live.phase==='reconnecting'?t('common.cancel'):t('live.leave')}</button></>:liveStatus?<button className="primary-button" onClick={openLive}><Headphones size={20}/>{live.phase==='error'?t('live.tryAgain'):t('live.listen')}</button>:<button className="secondary-button" onClick={()=>void refreshLive()}>{t('live.check')}</button>}</div>
 <SignalMeter samples={live.samples} level={live.level} active={live.listening} simple label={t('live.soundLabel')}/>
 {live.listening&&<div className="receiving-status">{live.volume===0?t('live.volumeOff'):live.level>-55?t('live.soundIncoming'):t('live.quietNow')}</div>}
 <div className="listener-volume"><label htmlFor="live-volume"><Volume2 size={18}/>{t('live.volume')}<span>{live.volume}%</span></label><Slider id="live-volume" aria-label={t('live.volumeAria')} value={[live.volume]} min={0} max={100} step={1} onValueChange={v=>live.setVolume(v[0])}/></div>

 </>}
 </section><aside className="live-info"><h3>{author?t('live.infoAuthor'):t('live.infoListener')}</h3>{author?<><p><Mic size={18}/>{t('live.authorTip1')}</p><p><Volume2 size={18}/>{t('live.authorTip2')}</p><p><Headphones size={18}/>{t('live.authorTip3')}</p></>:<><p><Headphones size={18}/>{t('live.listenerTip1')}</p><p><Volume2 size={18}/>{t('live.listenerTip2')}</p></>}{author&&<div className="pilot-note"><strong>{t('live.pilotTitle')}</strong><p>{t('live.pilotText')}</p>{author&&<p>{t('live.pilotNoRecord')}</p>}</div>}{!author&&live.phase==='error'&&<p>{t('live.otherNetwork')}</p>}</aside></div>}
 {view==='settings'&&<div className="settings-grid">
 <NotificationSettings author={author}/>
 <LanguageSettings/>
 {author?<>
 <section className="settings-panel"><div className="section-icon"><Heart size={22}/></div><h2>{t('settings.supportTitle')}</h2><p>{t('settings.supportText')}</p><label className="field">{t('settings.donationField')}<input type="url" value={donation} onChange={e=>setDonation(e.target.value)} placeholder="https://…"/></label><button className="primary-button" onClick={()=>void run(()=>api('library',{action:'donation',url:donation}),t('settings.donationSaved'))}><Check size={17}/>{t('settings.saveDonation')}</button><small>{t('settings.donationNote')}</small></section>
 <section className="settings-panel wide-panel"><div className="section-icon"><Link2 size={22}/></div><h2>{t('settings.linksTitle')}</h2><p>{t('settings.linksText')}</p><div className="links-grid">{SOCIALS.map(sc=><label className="field" key={sc.kind}>{t(sc.labelKey)}<input type="url" value={linkDraft[sc.kind]??''} placeholder="https://…" onChange={e=>setLinkDraft(prev=>({...prev,[sc.kind]:e.target.value}))}/></label>)}</div><button className="primary-button" onClick={()=>void run(()=>api('library',{action:'links',links:SOCIALS.map(sc=>({kind:sc.kind,url:(linkDraft[sc.kind]??'').trim()})).filter(l=>l.url)}),t('settings.linksSaved'))}><Check size={17}/>{t('settings.saveLinks')}</button><small>{t('settings.linksNote')}</small></section>
 </>:(!!data.donation||!!socialRow)&&<section className="settings-panel"><div className="section-icon"><Heart size={22}/></div><h2>{t('settings.authorTitle')}</h2><p>{t('settings.authorText')}</p>{supportCard}{socialRow}</section>}
 </div>}
 </>}
 <footer className="content-footer"><span>TRUE THRILLS</span><span>{t('desc.studio')}</span></footer>
 </main>
 {data&&!data.needsSetup&&<nav className="bottom-nav">
 <button className="bottom-nav-item" data-active={view==='podcasts'} aria-label={t('nav.podcasts')} onClick={()=>goto('podcasts')}><Headphones size={21}/><span>{t('nav.podcasts')}</span></button>
 <button className="bottom-nav-item" data-active={view==='videos'} aria-label={t('nav.videos')} onClick={()=>goto('videos')}><Video size={21}/><span>{t('nav.videos')}</span></button>
 <button className="bottom-nav-home" aria-label={t('nav.home')} onClick={()=>goto('home')}><img src="/brand/logo.png?v=0.4.1" width="66" height="66" alt=""/></button>
 <button className="bottom-nav-item" data-active={view==='stories'} aria-label={t('nav.stories')} onClick={()=>goto('stories')}><BookOpen size={21}/><span>{t('nav.stories')}</span></button>
 <button className="bottom-nav-item" data-active={view==='live'} aria-label={t('heading.live')} onClick={()=>goto('live')}>{liveStatus&&<span className="bottom-nav-dot"/>}<Radio size={21}/><span>{t('nav.live')}</span></button>
 </nav>}
 </div>
 <input type="file" accept="audio/*,.mp3,.wav,.m4a,.webm,.ogg,.flac" ref={fileInput} onChange={pickFile} hidden/>
 {playing&&<PodcastPlayer key={playing.id} src={'/api/audio?id='+playing.id} title={playing.title} duration={playing.duration} audioRef={player} onClose={()=>{player.current?.pause();setPlaying(null);}}/>}
 <Dialog open={!!editor} onOpenChange={o=>{if(!o&&!saving){setEditor(null);}}}><DialogContent className="editor-dialog" onInteractOutside={e=>{if(dirty||saving)e.preventDefault();}} onEscapeKeyDown={e=>{if(dirty||saving)e.preventDefault();}} showCloseButton={!saving&&!dirty}><DialogHeader><DialogTitle>{editing?t('editor.editing'):editor==='story'?t('editor.newStory'):editor==='video'?t('editor.newVideo'):t('editor.newPodcast')}</DialogTitle><DialogDescription>{editor==='story'?t('editor.storyHint'):editor==='video'?t('editor.videoHint'):t('editor.podcastHint')}</DialogDescription></DialogHeader><label className="field">{t('editor.title')}<input value={title} maxLength={160} onChange={e=>{setTitle(e.target.value);setDirty(true);}} placeholder={editor==='story'?t('editor.titleStory'):editor==='video'?t('editor.titleVideo'):t('editor.titleEpisode')}/></label><label className="field">{t('editor.description')}<textarea value={description} maxLength={2000} rows={2} onChange={e=>{setDescription(e.target.value);setDirty(true);}} placeholder={t('editor.descriptionPlaceholder')}/></label>{editor==='story'?<label className="field">{t('editor.storyText')}<textarea className="story-textarea" value={body} maxLength={150000} rows={10} onChange={e=>{setBody(e.target.value);setDirty(true);}} placeholder={t('editor.storyPlaceholder')}/></label>:editor==='video'?<><label className="field">{t('editor.videoUrl')}<input type="url" value={videoUrl} onChange={e=>{setVideoUrl(e.target.value);setDirty(true);}} placeholder="https://youtu.be/…"/></label>{!!videoUrl.trim()&&<VideoFrame url={videoUrl.trim()} title={title||t('editor.previewTitle')}/>}<small className="editor-hint">{t('editor.videoNote')}</small></>:<div className="audio-editor-preview"><FileAudio size={22}/><span>{editing?t('editor.audioOfEpisode'):capture.blob?t('editor.audioReady',{size:(capture.blob.size/1024/1024).toFixed(1)}):t('editor.audioMissing')}</span>{!editing&&capture.url&&<audio controls src={capture.url}/>}</div>}<div className="editor-actions"><button className="quiet-button" disabled={saving} onClick={()=>{if(dirty){setDiscardText(true);}else setEditor(null);}}>{t('common.cancel')}</button><button className="secondary-button" disabled={saving} onClick={()=>void save(false)}>{t('editor.toDrafts')}</button><button className="primary-button" disabled={saving} onClick={()=>void save(true)}>{saving?<Loader2 className="spin" size={17}/>:<ArrowUpRight size={17}/>} {saving?t('editor.saving'):t('editor.publish')}</button></div></DialogContent></Dialog>
 <Dialog open={!!reading} onOpenChange={o=>{if(!o)setReading(null);}}><DialogContent className="reading-dialog"><DialogHeader><DialogDescription>{t('reading.eyebrow')}</DialogDescription><DialogTitle>{reading?.title}</DialogTitle></DialogHeader>{reading?.description&&<p className="reading-intro">{reading.description}</p>}<div className="reading-body">{reading?.body}</div></DialogContent></Dialog>
 <Dialog open={!!watching} onOpenChange={o=>{if(!o)setWatching(null);}}><DialogContent className="video-dialog"><DialogHeader><DialogDescription>{t('watching.eyebrow')}</DialogDescription><DialogTitle>{watching?.title}</DialogTitle></DialogHeader>{!!watching?.videoUrl&&<VideoFrame url={watching.videoUrl} title={watching.title}/>}{!!watching?.description&&<p className="reading-intro">{watching.description}</p>}</DialogContent></Dialog>
 <AlertDialog open={!!confirmDelete} onOpenChange={o=>{if(!o)setConfirmDelete(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('confirm.deleteTitle',{title:confirmDelete?.title??''})}</AlertDialogTitle><AlertDialogDescription>{t('confirm.deleteText')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('common.cancel')}</AlertDialogCancel><AlertDialogAction onClick={()=>void run(()=>api('library',{action:'delete',id:confirmDelete?.id}),t('confirm.deleted'))}>{t('post.delete')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={discardText} onOpenChange={setDiscardText}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('confirm.discardTitle')}</AlertDialogTitle><AlertDialogDescription>{t('confirm.discardText')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('confirm.keepEditing')}</AlertDialogCancel><AlertDialogAction onClick={()=>{setEditor(null);setDirty(false);}}>{t('confirm.close')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={replaceRecording} onOpenChange={setReplaceRecording}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('confirm.replaceTitle')}</AlertDialogTitle><AlertDialogDescription>{t('confirm.replaceText')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('common.cancel')}</AlertDialogCancel><AlertDialogAction onClick={()=>void capture.start()}>{t('studio.startRecording')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
