'use client';
import {Mic,MicOff,RefreshCw,Volume2} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import type {useCapture} from '@/hooks/use-capture';
type Capture=ReturnType<typeof useCapture>;
export function InputPicker({capture,locked=false}:{capture:Capture;locked?:boolean}){
 const named=capture.devices.some(d=>d.label);
 return <div className="mic-setup"><label className="field">Как поступает звук<Select value={capture.mode} onValueChange={v=>capture.changeMode(v as 'mic'|'daw')} disabled={locked||capture.busy||!capture.settingsLoaded}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="mic">Микрофон / аудиоинтерфейс</SelectItem><SelectItem value="daw">Звук из FL Studio</SelectItem></SelectContent></Select></label>{capture.mode==='daw'&&<p className="audio-mode-help">Выбери CABLE Output. В FL Studio направь Master в CABLE Input, Stereo separation оставь по центру. Голос, музыка и эффекты поступят вместе.</p>}<div className="input-grid"><label>Источник звука<Select value={capture.device} onValueChange={v=>{capture.release();capture.setDevice(v);}} disabled={locked||capture.busy||capture.discovering}><SelectTrigger className="device-select"><SelectValue/></SelectTrigger><SelectContent>{capture.device!=='default'&&!capture.devices.some(d=>d.deviceId===capture.device)&&<SelectItem value={capture.device}>Сохранённый источник · обнови список</SelectItem>}<SelectItem value="default">Устройство Windows по умолчанию</SelectItem>{capture.devices.filter(d=>d.deviceId!=='default').map((d,i)=><SelectItem key={d.deviceId} value={d.deviceId}>{d.label||`Микрофон ${i+1}`}</SelectItem>)}</SelectContent></Select></label><label>Канал входа<Select value={capture.channel} onValueChange={v=>{capture.release();capture.setChannel(v);}} disabled={locked||capture.busy||capture.discovering}><SelectTrigger className="device-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0">Вход 1 → моно</SelectItem><SelectItem value="1">Вход 2 → моно</SelectItem><SelectItem value="stereo">Входы 1 + 2 → стерео</SelectItem></SelectContent></Select></label></div><div className="device-discovery"><button className={named?'quiet-button':'secondary-button'} disabled={locked||capture.discovering||capture.busy} onClick={()=>void capture.refreshDevices(!named)}><RefreshCw size={16}/>{capture.discovering?'Ищем устройства…':named?'Обновить устройства':'Разрешить микрофон и найти устройства'}</button>{!named&&<small>Доступ нужен только для списка входов. Запись не начнётся.</small>}</div></div>;
}
export function SignalMeter({samples,level,active,label,simple=false}:{samples:number[];level:number;active:boolean;label:string;simple?:boolean}){return <div className="signal-console"><div className="signal-head"><span>{label}</span>{!simple&&<strong className={active&&level>-3?'clipping':''}>{active?`${Math.round(level)} dBFS`:'Нет сигнала'}</strong>}</div><div className={'waveform '+(!active?'wave-inactive':'')} aria-label={label}>{samples.map((s,i)=><span key={i} style={{height:Math.max(3,Math.min(94,active?s*180+3:3))+'%'}}/>)}</div>{!simple&&<div className="meter-labels"><span>−60</span><span>−36</span><span>−18</span><span>−6</span><span>0 dBFS</span></div>}{!simple&&active&&level>-3&&<p className="clip-notice">Слишком громко. Уменьши усиление, чтобы избежать искажений.</p>}</div>;}
export function AudioControls({capture}:{capture:Capture}){return <div className="audio-controls-panel"><div className="gain-control"><div><label htmlFor="input-gain">Усиление входящего звука</label><strong>{capture.gainDb>0?'+':''}{capture.gainDb} dB</strong></div><Slider id="input-gain" aria-label="Усиление входящего звука" value={[capture.gainDb]} min={-18} max={12} step={1} onValueChange={v=>capture.setGainDb(v[0])}/></div><div className="mic-toggles"><label><Switch checked={capture.muted} onCheckedChange={capture.setMuted}/>{capture.muted?<MicOff size={16}/>:<Mic size={16}/>}Выключить весь входящий звук</label><label><Switch checked={capture.lowCut} onCheckedChange={capture.setLowCut}/><Volume2 size={16}/>Срез низких частот · 80 Гц</label></div></div>;}
