'use client';
import {Mic,MicOff,RefreshCw,Volume2} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import type {useCapture} from '@/hooks/use-capture';
import {useT} from '@/components/i18n-provider';
type Capture=ReturnType<typeof useCapture>;
export function InputPicker({capture,locked=false}:{capture:Capture;locked?:boolean}){
 const {t}=useT();
 const named=capture.devices.some(d=>d.label);
 return <div className="mic-setup"><label className="field">{t('input.howSound')}<Select value={capture.mode} onValueChange={v=>capture.changeMode(v as 'mic'|'daw')} disabled={locked||capture.busy||!capture.settingsLoaded}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="mic">{t('input.mic')}</SelectItem><SelectItem value="daw">{t('input.daw')}</SelectItem></SelectContent></Select></label>{capture.mode==='daw'&&<p className="audio-mode-help">{t('input.dawHelp')}</p>}<div className="input-grid"><label>{t('input.source')}<Select value={capture.device} onValueChange={v=>{capture.release();capture.setDevice(v);}} disabled={locked||capture.busy||capture.discovering}><SelectTrigger className="device-select"><SelectValue/></SelectTrigger><SelectContent>{capture.device!=='default'&&!capture.devices.some(d=>d.deviceId===capture.device)&&<SelectItem value={capture.device}>{t('input.savedSource')}</SelectItem>}<SelectItem value="default">{t('input.systemDefault')}</SelectItem>{capture.devices.filter(d=>d.deviceId!=='default').map((d,i)=><SelectItem key={d.deviceId} value={d.deviceId}>{d.label||t('input.micNumbered',{number:i+1})}</SelectItem>)}</SelectContent></Select></label><label>{t('input.channel')}<Select value={capture.channel} onValueChange={v=>{capture.release();capture.setChannel(v);}} disabled={locked||capture.busy||capture.discovering}><SelectTrigger className="device-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0">{t('input.channel1')}</SelectItem><SelectItem value="1">{t('input.channel2')}</SelectItem><SelectItem value="stereo">{t('input.channelStereo')}</SelectItem></SelectContent></Select></label></div><div className="device-discovery"><button className={named?'quiet-button':'secondary-button'} disabled={locked||capture.discovering||capture.busy} onClick={()=>void capture.refreshDevices(!named)}><RefreshCw size={16}/>{capture.discovering?t('input.searching'):named?t('input.refreshDevices'):t('input.allowAndFind')}</button>{!named&&<small>{t('input.listOnlyNote')}</small>}</div></div>;
}
export function SignalMeter({samples,level,active,label,simple=false}:{samples:number[];level:number;active:boolean;label:string;simple?:boolean}){const {t}=useT();return <div className="signal-console"><div className="signal-head"><span>{label}</span>{!simple&&<strong className={active&&level>-3?'clipping':''}>{active?`${Math.round(level)} dBFS`:t('input.noSignal')}</strong>}</div><div className={'waveform '+(!active?'wave-inactive':'')} aria-label={label}>{samples.map((s,i)=><span key={i} style={{height:Math.max(3,Math.min(94,active?s*180+3:3))+'%'}}/>)}</div>{!simple&&<div className="meter-labels"><span>−60</span><span>−36</span><span>−18</span><span>−6</span><span>0 dBFS</span></div>}{!simple&&active&&level>-3&&<p className="clip-notice">{t('input.tooLoud')}</p>}</div>;}
export function AudioControls({capture}:{capture:Capture}){const {t}=useT();return <div className="audio-controls-panel"><div className="gain-control"><div><label htmlFor="input-gain">{t('input.gain')}</label><strong>{capture.gainDb>0?'+':''}{capture.gainDb} dB</strong></div><Slider id="input-gain" aria-label={t('input.gain')} value={[capture.gainDb]} min={-18} max={12} step={1} onValueChange={v=>capture.setGainDb(v[0])}/></div><div className="mic-toggles"><label><Switch checked={capture.muted} onCheckedChange={capture.setMuted}/>{capture.muted?<MicOff size={16}/>:<Mic size={16}/>}{t('input.muteAll')}</label><label><Switch checked={capture.lowCut} onCheckedChange={capture.setLowCut}/><Volume2 size={16}/>{t('input.lowCut')}</label></div></div>;}
