import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
const built=await build({entryPoints:['lib/usage.ts'],bundle:true,write:false,platform:'node',format:'esm'});
let code=built.outputFiles[0].text;
if(process.env.TT_USAGE_MUTATION==='1')code=code.replace('if (!accepted.changes) return false;','');
const {recordUsage}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const sqlite=new DatabaseSync(':memory:');
sqlite.exec("CREATE TABLE posts(id TEXT PRIMARY KEY,kind TEXT,published INTEGER);CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE rate_limits(id TEXT PRIMARY KEY,attempts INTEGER,expires_at INTEGER);INSERT INTO posts VALUES('a','podcast',1),('s','story',1),('v','video',1),('d','story',0)");
const db={prepare:s=>sqlite.prepare(s),transaction:fn=>()=>{sqlite.exec('BEGIN');try{const r=fn();sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
assert.equal(recordUsage(db,'a','session1',1000),true);
assert.equal(recordUsage(db,'a','session1',1001),false,'duplicate session must not count twice');
assert.equal(recordUsage(db,'a','session2',1002),true);
assert.equal(recordUsage(db,'s','session1',1003),true);
for(const id of ['v','d','missing'])assert.equal(recordUsage(db,id,'session1',1004),false,'invalid kind/draft must not count');
assert.equal(sqlite.prepare("SELECT value FROM settings WHERE key='usage:a'").get().value,'2');
assert.equal(recordUsage(db,'a','session1',86401001),true,'expired dedup window must allow new event');
assert.equal(sqlite.prepare("SELECT value FROM settings WHERE key='usage:a'").get().value,'3');
sqlite.close();console.log('PASS usage: atomic totals, duplicate rejection, expiry, drafts/video/missing exclusions');
